pipeline{
 agent none
    stages{
       stage('frontend'){
             agent{
                docker{image 'maven:3.8.1-adoptopenjdk-11'}
             }
             steps{
                  sh 'mvn --version'
                  sh 'javac hello.java'
                  sh 'java hello.java'
             }
       }

       
             
    }
}
